[package]
name = "tauri-plugin-ankidroid-api"
version = "0.1.0"
authors = ["Tauri Plugin AnkiDroid API"]
description = "Tauri plugin for accessing AnkiDroid content provider on Android"
edition = "2021"
rust-version = "1.60"
links = "tauri-plugin-ankidroid-api"

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"

[build-dependencies]
tauri-plugin = { version = "2.0", features = ["build"] }